Replace __BEGIN_DECLS and __END_DECLS with extern "C".
libcgroup/libcgroup pull request #45
Opened 2021-05-20 15:31 UTC by Hello71

The macros __BEGIN_DECLS and __END_DECLS are a GNU-ism found in
glibc and uClibc, but not musl.  We replace them by the more general
extern "C" { ... } block exposed only if we have __cplusplus.

Forward ported from a patch by Anthony G. Basile <blueness@gentoo.org>.

2021-05-24 19:29 UTC, drakenclimber commented
Thanks for the submission, @Hello71.  The changes look good to me.

Could you please add your signed-off-by to the commit?  Now that we're getting more community contributions, I have a review out for contributions guidelines.  The proposed guidelines are available here:
https://github.com/drakenclimber/libcgroup/blob/issues/contributing/CONTRIBUTING.md

Thanks.

2021-05-24 20:57 UTC, Hello71 commented
done

2021-05-24 21:01 UTC, giani requested changes
@Hello71 - If this was a patch written by Anthony - can you please retain is "From" so Anthony gets the appropriate credit.

2021-05-24 21:14 UTC, Hello71 commented
original patch: https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-libs/libcgroup/files/libcgroup-0.41-replace_DECLS.patch

but concept of __BEGIN_DECLS being for internal use only is not new, nor is this fix. ianal but i think sed -i -e 's/__BEGIN_DECLS/#ifdef __cplusplus\nextern "C" {\n#endif/' etc is not copyrightable. i added the comments to fit better with rest of code style, but i don't really care about that, you can remove it if you want, or write your own patch.

2021-07-06 15:14 UTC, drakenclimber commented
Thanks @Hello71.  Code has been merged in commit 215974e67a24edf9097507e8707190b6a42c7207

2021-07-06 15:14 UTC, closed without merging